/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author juald
 */
public class VistaMonitor extends javax.swing.JPanel {

    /**
     * Creates new form VistaMonitor
     */
    public VistaMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMonitor = new javax.swing.JTable();
        jButtonAddMonitor = new javax.swing.JButton();
        jButtonDeleteMonitor = new javax.swing.JButton();
        jButtonUpdateMonitor = new javax.swing.JButton();
        jLabelGestionDeMonitores = new javax.swing.JLabel();

        TablaMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaMonitor);

        jButtonAddMonitor.setText("Nuevo Monitor");
        jButtonAddMonitor.setActionCommand("NuevoMonitor");

        jButtonDeleteMonitor.setText("Baja de Monitor");
        jButtonDeleteMonitor.setActionCommand("BajaMonitor");

        jButtonUpdateMonitor.setText("Actualización de Monitor");
        jButtonUpdateMonitor.setActionCommand("ActualizacionMonitor");

        jLabelGestionDeMonitores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelGestionDeMonitores.setText("Gestión de Monitores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGestionDeMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateMonitor)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelGestionDeMonitores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMonitor)
                    .addComponent(jButtonDeleteMonitor)
                    .addComponent(jButtonUpdateMonitor))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaMonitor;
    public javax.swing.JButton jButtonAddMonitor;
    public javax.swing.JButton jButtonDeleteMonitor;
    public javax.swing.JButton jButtonUpdateMonitor;
    public javax.swing.JLabel jLabelGestionDeMonitores;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
