/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author juald
 */
public class VistaGestionActividades extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestionActividades
     */
    public VistaGestionActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGestionDeActividades = new javax.swing.JLabel();
        jScrollPaneTablaSocios = new javax.swing.JScrollPane();
        jTableGestionDeActividades = new javax.swing.JTable();
        jButtonDarAlta = new javax.swing.JButton();
        jButtonDarBaja = new javax.swing.JButton();
        jTextFieldSeleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxBaja = new javax.swing.JComboBox<>();
        jComboBoxActividadesDisponibles = new javax.swing.JComboBox<>();

        jLabelGestionDeActividades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelGestionDeActividades.setText("Gestión de Actividades");

        jTableGestionDeActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTablaSocios.setViewportView(jTableGestionDeActividades);

        jButtonDarAlta.setText("Dar de Alta");
        jButtonDarAlta.setActionCommand("DardeAlta");

        jButtonDarBaja.setText("Dar de Baja");
        jButtonDarBaja.setActionCommand("DardeBaja");

        jLabel1.setText("Socio seleccionado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTablaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGestionDeActividades))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSeleccionado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDarAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDarBaja, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxActividadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelGestionDeActividades)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTablaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDarBaja)
                    .addComponent(jTextFieldSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDarAlta)
                    .addComponent(jComboBoxActividadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonDarAlta;
    public javax.swing.JButton jButtonDarBaja;
    public javax.swing.JComboBox<String> jComboBoxActividadesDisponibles;
    public javax.swing.JComboBox<String> jComboBoxBaja;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelGestionDeActividades;
    private javax.swing.JScrollPane jScrollPaneTablaSocios;
    public javax.swing.JTable jTableGestionDeActividades;
    public javax.swing.JTextField jTextFieldSeleccionado;
    // End of variables declaration//GEN-END:variables
}
